#!/bin/bash

function check () (
    PROGRAM="$1"
    CURRENT="$2"
    LATEST="$3"
    if   test "$LATEST" == "$CURRENT"
    then :
    else echo "A new version of $PROGRAM has been released ($CURRENT -> $LATEST)"
    fi
)

#check  PROGRAM     CURRENT     LATEST
check   "Nano"      "6.2"       "$( wget https://www.nano-editor.org -O - 2> /dev/null | head -n +23 | tail -n +23 | cut -d'&' -f1 )"
check   "Anki"      "2.1.50"    "$( wget https://github.com/ankitects/anki/releases/tag/2.1.50 -O - 2> /dev/null | egrep "<title>Release.*" -o | cut -d' ' -f2 )"
check   "Octave"    "6.4.0"     "$( wget https://www.gnu.org/software/octave/feed.xml -O - 2> /dev/null | tail -n  +13 | head -n +1 | cut -b 27-31 )"
check   "Julia"     "v1.6.1"    "$( wget https://github.com/JuliaLang/julia/releases/latest -O - 2> /dev/null | egrep "<title>Release.*" -o | cut -d' ' -f2 )"
check   "Jabref"    "5.2"       "$( wget https://github.com/JabRef/jabref/releases/latest -O - 2> /dev/null | egrep "<title>Release.*" -o | cut -d' ' -f4 )"
check   "Zoom"      "5.6.4"     "$( wget https://zoom.us/download -O - 2> /dev/null | egrep "var packageVersionX64" | egrep "Version .*" -o | cut -d' ' -f2 )"
